apiVersion: skaffold/v1
kind: Config
metadata:
  name: events
build:
  artifacts:
  - image: wdalmut/conf-informer
    context: conf-informer
    docker:
      dockerfile: Dockerfile
  - image: wdalmut/conf-consumer
    context: conf-consumer
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - ./k8s/namespace.yaml
      - ./k8s/*
