apiVersion: skaffold/v1
kind: Config
metadata:
  name: events
build:
  artifacts:
  - image: wdalmut/conf-informer
    context: src/conf-informer
    docker:
      dockerfile: Dockerfile
  - image: wdalmut/conf-consumer
    context: src/conf-consumer
    docker:
      dockerfile: Dockerfile
  - image: wdalmut/conf-order-validate
    context: src/order-validate
    docker:
      dockerfile: Dockerfile
  - image: wdalmut/conf-order-informer
    context: src/order-informer
    docker:
      dockerfile: Dockerfile
  - image: wdalmut/conf-order-consumer
    context: src/order-consumer
    docker:
      dockerfile: Dockerfile
  - image: wdalmut/conf-order-consumer-upd
    context: src/order-consumer-upd
    docker:
      dockerfile: Dockerfile
  - image: wdalmut/conf-order-consumer-del
    context: src/order-consumer-del
    docker:
      dockerfile: Dockerfile
  - image: wdalmut/conf-payment-gateway-paypal
    context: src/payment-gateway-paypal
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - ./k8s/namespace.yaml
    - ./k8s/*
