apiVersion: apps/v1
kind: Deployment
metadata:
  name: conf-order-informer
  namespace: kconference
spec:
  selector:
    matchLabels:
      app: conf-order-informer
  replicas: 1
  template:
    metadata:
      labels:
        app: conf-order-informer
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: conf-order-informer-service-account
      containers:
      - name: conf-order-informer
        image: wdalmut/conf-order-informer
        env:
          - name: REDIS_HOST
            value: "queue-service"
          - name: ADD_QUEUE_NAME
            value: 'add-order'
          - name: UPDATE_QUEUE_NAME
            value: 'update-order'
          - name: DELETE_QUEUE_NAME
            value: 'delete-order'

