apiVersion: apps/v1
kind: Deployment
metadata:
  name: conf-informer
  namespace: kconference
spec:
  selector:
    matchLabels:
      app: conf-informer
  replicas: 1
  template:
    metadata:
      labels:
        app: conf-informer
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: conf-informer-service-account
      containers:
      - name: conf-informer
        image: wdalmut/conf-informer
        env:
          - name: REDIS_HOST
            value: "queue-service"
          - name: ADD_QUEUE_NAME
            value: 'add-conf'
          - name: DELETE_QUEUE_NAME
            value: 'delete-conf'
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "128Mi"
            cpu: "128m"
