apiVersion: apps/v1
kind: Deployment
metadata:
  name: conf-consumer
  namespace: kconference
spec:
  selector:
    matchLabels:
      app: conf-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: conf-consumer
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: conf-consumer-service-account
      containers:
      - name: conf-consumer
        image: wdalmut/conf-consumer
        env:
          - name: REDIS_HOST
            value: "queue-service"
          - name: ADD_QUEUE_NAME
            value: 'add-conf'
          - name: ADD_PROCESSING_QUEUE_NAME
            value: 'processing-add-conf'

