apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-conf-consumer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-conf-consumer
subjects:
  - kind: ServiceAccount
    name: conf-consumer-service-account
    namespace: kconference


