apiVersion: v1
kind: Service
metadata:
  name: orders-validate-service
  namespace: kconference
spec:
  selector:
    app: conf-order-validate
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443

