apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-conf-order-validate-role-binding
  namespace: kconference
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: conf-order-validate-role
subjects:
  - kind: ServiceAccount
    name: conf-order-validate-service-account
    namespace: kconference


