apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conf-order-validate-role
rules:
- apiGroups:
  - "app.corley.it"
  resources:
  - "plans"
  - "coupons"
  verbs:
  - "get"
  - "list"

