apiVersion: apps/v1
kind: Deployment
metadata:
  name: conf-consumer-del
  namespace: kconference
spec:
  selector:
    matchLabels:
      app: conf-consumer-del
  replicas: 1
  template:
    metadata:
      labels:
        app: conf-consumer-del
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: conf-consumer-del-service-account
      containers:
      - name: conf-consumer-del
        image: wdalmut/conf-consumer-del
        env:
          - name: REDIS_HOST
            value: "queue-service"
          - name: DELETE_QUEUE_NAME
            value: 'delete-conf'
          - name: DELETE_PROCESSING_QUEUE_NAME
            value: 'processing-delete-conf'
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "128Mi"
            cpu: "128m"


