apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: orders.app.corley.it
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: app.corley.it
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                planRef:
                  type: string
                couponRef:
                  type: string
                price:
                  type: number
                date:
                  type: string
                quantity:
                  type: integer
                status:
                  type: string
      additionalPrinterColumns:
      - name: plan
        type: string
        description: The current purchase plan
        jsonPath: .spec.planRef
      - name: coupon
        type: string
        description: The purchase coupon code
        jsonPath: .spec.couponRef
      - name: status
        type: string
        description: The order status
        jsonPath: .spec.status
      - name: price
        type: number
        description: The order total price
        jsonPath: .spec.price
      - name: date
        type: string
        description: The order purchase date
        jsonPath: .spec.date
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: orders
    # singular name to be used as an alias on the CLI and for display
    singular: order
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Order
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ord

