apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "order-policy.app.corley.it"
webhooks:
- name: "order-policy.app.corley.it"
  rules:
  - apiGroups:   ["app.corley.it"]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["orders"]
    scope:       "Namespaced"
  clientConfig:
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYVENDQWtXZ0F3SUJBZ0lVRVlWa0dGNkJaR0YvTGZjUHc5UFZzbkRLQXQ0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1BqRUxNQWtHQTFVRUJoTUNTVlF4RGpBTUJnTlZCQWdNQlVsMFlXeDVNUTR3REFZRFZRUUhEQVZVZFhKcApiakVQTUEwR0ExVUVDZ3dHUTI5eWJHVjVNQjRYRFRJd01ESXhOVEl4TURRME1Gb1hEVE13TURJeE1qSXhNRFEwCk1Gb3dQakVMTUFrR0ExVUVCaE1DU1ZReERqQU1CZ05WQkFnTUJVbDBZV3g1TVE0d0RBWURWUVFIREFWVWRYSnAKYmpFUE1BMEdBMVVFQ2d3R1EyOXliR1Y1TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQwpBUUVBdHVabndhOUdqUjRzU1dNajVXMXpta0JMVkFLcEN0a2FZbUo4d2RtTDZIUWpzM0xLMGluQXhEeVdTcDIvCnRvTkVJV2lLVVhad1cyR3JZUkt3RWg4ODlnWWxCajFpdFlYQ2hmTC9HcUxDL2dlLytTSXNiQnVNRFZjN2JRZjUKTkc3YXFsdndpdUMrWWVCcHA4VXVqcUZ2U25lM3FrTFVldzk3SDdYd1hYVjkwRVBHUGdhUVMxcDJLZXkraGNhTgpCbk1kV2pTUHRqUjgyb3k2MWEzcnFiQ2crK2E0VTVieVRVWVBpaFVBazFwZUNBaHZZdkZZbk44UERHbmdIaUNMCkZuVHQ5dG5aZzZMZjkyeVlaeTNJMUN2MDAvMDJSeGpsRzBTZW1Wb3NHVlFwcE9GTk9BZExLdjN2RCtTWUZDWWUKQXFrNUxkM3pYU0lWRCt4WEgxQUVSYXpqUVFJREFRQUJvMU13VVRBZEJnTlZIUTRFRmdRVXdTSU81QjhEdG05UgpYbEdiTmFBSlRhb2RSSU13SHdZRFZSMGpCQmd3Rm9BVXdTSU81QjhEdG05UlhsR2JOYUFKVGFvZFJJTXdEd1lEClZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBYVdtTlRvN041eFl1Unpad01qYjAKZ0hrWFR2UEk2UitrODN4cDh0V21uUkloRVBFQjVkbURVOGlHK1J0NTk2Uy9TUUxKTkRRbks1ekFmQjVUUDVZRAo2RHoyRVM3bVNLZXNTMWlndExmcVFDbE9rYW5QajcxdkxXdnFsdHA3QlloaVZibU9HRjAybGdoV2sveEJaWVpMCmJpcHp5WjZSeHNsL2ZHYU1zMVRTMDd2WWNzOFFuMjBsY1hJWXdHLzRRMWJyS0toVHZod240SFY1c3ZQNmdibVcKNFp2a3RKS2NvQUJiY1gzN1hzcUFLblZEWTNjYUhQUEF1dTl2UUhadlBya0JOQm9FZ29YMTRIVTFRaElLV3BwawpvQ0gwdGhJbkRnSFp4N2hlVlpjYzRvaUN2eUx2WnN3UU1GdHV6cjFDeWdZKzJwSE1DRjh3RUp1a0tBL29uTklpCjhnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    service:
      namespace: "kconference"
      name: "orders-validate-service"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 3
