apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: tickets.app.corley.it
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: app.corley.it
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["orderRef", "code"]
              properties:
                orderRef:
                  type: string
                code:
                  type: string
                  pattern: '^[0-9]{7}$'
                attendee:
                  type: object
                  required: ["firstname", "lastname"]
                  properties:
                    firstname:
                      type: string
                      pattern: '[a-zA-Z ]+'
                    lastname:
                      type: string
                      pattern: '[a-z-A-Z ]+'
      additionalPrinterColumns:
      - name: order
        type: string
        description: The current source order
        jsonPath: .spec.orderRef
      - name: code
        type: string
        description: The current ticket code
        jsonPath: .spec.code
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: tickets
    # singular name to be used as an alias on the CLI and for display
    singular: ticket
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Ticket
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - tck


