apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-order-consumer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-order-consumer
subjects:
  - kind: ServiceAccount
    name: order-consumer-service-account
    namespace: kconference



