apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-order-consumer
rules:
- apiGroups:
  - "app.corley.it"
  resources:
  - "orders"
  - "orders/status"
  - "tickets"
  verbs:
  - "*"


