apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: payment-informer-role
rules:
- apiGroups:
  - "events.k8s.io"
  resources:
  - "events"
  verbs:
  - "get"
  - "list"
  - "watch"


