apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-payment-informer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: payment-informer-role
subjects:
  - kind: ServiceAccount
    name: payment-informer-service-account
    namespace: kconference


