apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  namespace: kconference
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template:
    metadata:
      labels:
        app: queue
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: redis
        image: redis:5

